apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-go-rhtap-three-component-scenarios-abwi
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-glbk-tenant/mc-three-scenarios/devfile-go-rhtap-three-component-scenarios-abwi@sha256:5427843e0a2b3c47406104be95f9bfee7d85a496425a739ff8fa4df6c6f39670
        name: my-go
        resources: {}
status: {}
